### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by lsvih** [DistriNet/DLWF#1]
Hi there,

While download closed-world dataset(https://distrinet.cs.kuleuven.be/software/tor-wf-dl/files/tor_100w_2500tr.npz), I found that there has some 'None' label in it, which caused error "expected dense_1 to have shape (100,) but got array with shape (101,)". Could you give some advices about this?

And, npz files you provided can be used directly, so is folder 'preprogress' unnecessary?

**Comment by smith0818** [comment]
Hello,i met with the same problem as you.Did you solve it?

**Comment by verarim** [comment]
Hi, please check the updated file, should be fine now.

**Comment by smith0818** [comment]
> 嗨，请检查更新的文件，现在应该可以了。



> Hi, please check the updated file, should be fine now.

Sorry,I still can't find updated code.Maybe it‘s because I have just used Git-hub. Can you elaborate more?

**Comment by verarim** [comment]
> > 嗨，请检查更新的文件，现在应该可以了。
> 
> > Hi, please check the updated file, should be fine now.
> 
> Sorry,I still can't find updated code.Maybe it‘s because I have just used Git-hub. Can you elaborate more?

The code is not updated, only the numpy file is re-uploaded (https://distrinet.cs.kuleuven.be/software/tor-wf-dl/files/tor_100w_2500tr.npz). There were a couple of empty records in the end, which broke the parser. Now it should be all fine, but please let me know if there are issues still.
